language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '11'
before_script:
  - echo 'Europe/Amsterdam' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
script:
  - npm run test:prod
after_success:
  - npm run travis-deploy-once "npm run report-coverage"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
