name: Node CI
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  release:
    name: Build, test, and release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 16
      - name: Cache node modules
        uses: actions/cache@v3.0.11
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Build TypeScript
        run: npm run build
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: "Koj Bot"
          GIT_AUTHOR_EMAIL: "bot@koj.co"
          GIT_COMMITTER_NAME: "Koj Bot"
          GIT_COMMITTER_EMAIL: "bot@koj.co"
