name: Test CI
on:
  push:
    branches-ignore:
      - master
jobs:
  release:
    name: Build and test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npx npm@latest ci
      - name: Test
        run: npm test -- --runInBand
      - name: Build TypeScript
        run: npm run build
